@ECHO off

COLOR 17
CHOICE /C 1234567 /M "Enter your Choice 1, 2, 3, 4, 5, 6 or 7" /N
::
IF ERRORLEVEL 7 ECHO STOP
IF ERRORLEVEL 6  ECHO SIX
IF ERRORLEVEL 5  ECHO HIGH FIVE
IF ERRORLEVEL 4  ECHO FOUR
IF ERRORLEVEL 3  ECHO THREE
IF ERRORLEVEL 2  ECHO TWO
IF ERRORLEVEL 1  ECHO ONE
::